version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/quiz-app
      - PORT=3000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mongo:6.0
    container_name: quiz-app-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
